version: "3.8"
services:
  main:
    build:
      context: ifbe
      target: development
    volumes:
      - ./ifbe:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:3000
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
      - swift
  postgres:
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/1-db-init.sql
  swift:
    image: morrisjobke/docker-swift-onlyone
    networks:
      - webnet
    volumes:
      - swift_data:/srv
    environment:
      SWIFT_DEFAULT_CONTAINER: CLIENT_TOKENS
networks:
  webnet:
volumes:
  pgdata:
  swift_data:
