version: "3.8"
services:
#  main:
#    build:
#      context: ifbe
#      target: development
#    volumes:
#      - ./ifbe:/usr/src/app
#      - /usr/src/app/node_modules
#    ports:
#      - ${SERVER_PORT}:${SERVER_PORT}
#      - 9229:9229
#    command: npm run start:dev
#    env_file:
#      - .env
#    networks:
#      - webnet
#    depends_on:
#      - postgres
#      - swift
  postgres:
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/1-db-init.sql
    ports:
      - 5115:5432
#  swift:
#    image: morrisjobke/docker-swift-onlyone
#    networks:
#      - webnet
#    volumes:
#      - swift_data1:/srv
#    ports:
#      - 8055:8080
  s3:
    image: adobe/s3mock
    networks:
      - webnet
    volumes:
      - s3_data:/srv
    environment:
      initialBuckets: client_media
      root: /srv
    ports:
      - 9090:9090
networks:
  webnet:
volumes:
  pgdata:
  s3_data:
